#!/usr/bin/env python3
"""
Figma to Jetpack Compose Generator
Converts Figma designs to Kotlin Compose code
"""

import requests
import json
import sys
import os
from pathlib import Path
from typing import Dict, List, Any, Optional

# Load environment variables
from dotenv import load_dotenv

# Load .env file
env_path = Path(__file__).parent.parent / ".env"
load_dotenv(env_path)

FIGMA_API_TOKEN = os.getenv("FIGMA_API_TOKEN")
FIGMA_API_URL = "https://api.figma.com/v1"


class FigmaToCompose:
    def __init__(self, token: str):
        self.token = token
        self.headers = {
            "X-Figma-Token": token,
            "Content-Type": "application/json"
        }

    def get_file(self, file_id: str) -> Dict[str, Any]:
        """Fetch Figma file data"""
        url = f"{FIGMA_API_URL}/files/{file_id}"
        response = requests.get(url, headers=self.headers)
        if response.status_code != 200:
            print(f"❌ Error fetching file: {response.status_code}")
            print(response.text)
            sys.exit(1)
        return response.json()

    def parse_node(self, node: Dict[str, Any], depth: int = 0) -> str:
        """Parse a Figma node and convert to Compose code"""
        indent = "    " * depth
        compose_code = ""

        node_type = node.get("type", "")
        node_name = node.get("name", "Unknown")

        # Extract properties
        width = node.get("absoluteBoundingBox", {}).get("width", "Modifier")
        height = node.get("absoluteBoundingBox", {}).get("height", "Modifier")
        fill = node.get("fills", [{}])[0] if node.get("fills") else {}

        if node_type == "TEXT":
            content = node.get("characters", "Text")
            font_size = node.get("fontSize", 16)
            compose_code += f'{indent}Text(\n'
            compose_code += f'{indent}    text = "{content}",\n'
            compose_code += f'{indent}    fontSize = {int(font_size)}.sp\n'
            compose_code += f'{indent})\n'

        elif node_type == "RECTANGLE":
            compose_code += f'{indent}Box(\n'
            compose_code += f'{indent}    modifier = Modifier\n'
            compose_code += f'{indent}        .size({int(width)}.dp, {int(height)}.dp)\n'
            compose_code += f'{indent}        .background(Color.Gray)\n'
            compose_code += f'{indent})\n'

        elif node_type == "FRAME" or node_type == "GROUP":
            children = node.get("children", [])
            if children:
                compose_code += f'{indent}Column(\n'
                compose_code += f'{indent}    modifier = Modifier\n'
                compose_code += f'{indent}        .fillMaxWidth()\n'
                compose_code += f'{indent}        .padding(16.dp)\n'
                compose_code += f'{indent})\n{indent}{{\n'
                for child in children:
                    compose_code += self.parse_node(child, depth + 1)
                compose_code += f'{indent}}}\n'

        elif node_type == "COMPONENT":
            compose_code += f'{indent}// Component: {node_name}\n'
            compose_code += f'{indent}Card(modifier = Modifier.fillMaxWidth()) {{\n'
            children = node.get("children", [])
            for child in children:
                compose_code += self.parse_node(child, depth + 1)
            compose_code += f'{indent}}}\n'

        return compose_code

    def generate_compose(self, file_id: str, node_id: Optional[str] = None) -> str:
        """Generate Compose code from Figma file"""
        print(f"🎨 Fetching Figma design ({file_id})...")
        file_data = self.get_file(file_id)

        compose_code = '// Auto-generated from Figma design\n// Generated by figma_to_compose.py\n\n'
        compose_code += '@Composable\nfun FigmaDesign() {\n'
        compose_code += '    Column(\n'
        compose_code += '        modifier = Modifier\n'
        compose_code += '            .fillMaxSize()\n'
        compose_code += '            .padding(16.dp),\n'
        compose_code += '        verticalArrangement = Arrangement.spacedBy(8.dp)\n'
        compose_code += '    ) {\n'

        # Parse document nodes
        document = file_data.get("document", {})
        children = document.get("children", [])

        for child in children:
            compose_code += self.parse_node(child, depth=2)

        compose_code += '    }\n'
        compose_code += '}\n'

        return compose_code


def main():
    if not FIGMA_API_TOKEN:
        print("❌ Error: FIGMA_API_TOKEN not found in .env file")
        print("Run: ./setup-mcp.sh to configure")
        sys.exit(1)

    # Extract file ID from Figma URL
    file_id = "Q1j2NHKKaA3AnLd2LMCi07"

    print("━" * 60)
    print("🎨 FIGMA TO JETPACK COMPOSE CONVERTER")
    print("━" * 60)

    converter = FigmaToCompose(FIGMA_API_TOKEN)

    try:
        compose_code = converter.generate_compose(file_id)

        print("\n✅ Generated Compose Code:\n")
        print(compose_code)

        # Save to file
        output_file = Path(__file__).parent.parent / "generated_figma_compose.kt"
        with open(output_file, "w") as f:
            f.write(compose_code)

        print(f"\n💾 Saved to: {output_file}")

    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()

